[font]
size = 11.0

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[cursor]
style = { shape = "Underline", blinking = "On" }

[keyboard]
bindings = [
   { key = "T", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[window]
padding = { x = 10, y = 10 }

[colors.primary]
background = '#202020'
foreground = '#c2c2b0'

[colors.normal]
black   = '#151515'
red     = '#b44242'
green   = '#95a328'
yellow  = '#e1c135'
blue    = '#60928f'
magenta = '#7c435a'
cyan    = '#a48b4a'
white   = '#c2c2b0'

[colors.bright]
black  = '#3f3639'
red    = '#dc7671'
green  = '#e8e85a'
yellow = '#9e9052'
blue   = '#76c39b'
magenta= '#86596c'
cyan   = '#ceb34f'
white  = '#b0afa8'
