import = [
"~/.config/alacritty/hellfire.toml",
]

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[cursor]
style = { shape = "Underline", blinking = "On" }

[keyboard]
bindings = [
   { key = "T", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[window]
padding = { x = 10, y = 10 }
