[colors.primary]
background = '#202020'
foreground = '#c2c2b0'

[colors.normal]
black   = '#151515'
red     = '#b44242'
green   = '#95a328'
yellow  = '#e1c135'
blue    = '#60928f'
magenta = '#7c435a'
cyan    = '#a48b4a'
white   = '#c2c2b0'

[colors.bright]
black  = '#3f3639'
red    = '#dc7671'
green  = '#e8e85a'
yellow = '#9e9052'
blue   = '#76c39b'
magenta= '#86596c'
cyan   = '#ceb34f'
white  = '#b0afa8'