[colors.primary]
background = '#141414'
foreground = '#c9c9c9'

[colors.normal]
black =   '#191918'
red =     '#b34538'
green =   '#587744'
yellow =  '#d08949'
blue =    '#206ec5'
magenta = '#864651'
cyan =    '#ac9166'
white =   '#f1eee7'

[colors.bright]
black =   '#2c2b2a'
red =     '#b33323'
green =   '#42824a'
yellow =  '#c75a22'
blue =    '#5389c5'
magenta = '#e795a5'
cyan =    '#ebc587'
white =   '#ffffff'

