[colors.primary]
background = '#0d0d0d'
foreground = '#dfdddd'

[colors.normal]
black =   '#1b1b1b'
red =     '#c14d53'
green =   '#56966e'
yellow =  '#dc8c61'
blue =    '#6e95bd'
magenta = '#a56db1'
cyan =    '#6a9f98'
white =   '#b7b7b7'

[colors.bright]
black =   '#272727'
red =     '#da4b52'
green =   '#57a274'
yellow =  '#e1956c'
blue =    '#6fadea'
magenta = '#d466e9'
cyan =    '#63b4b5'
white =   '#a4b5b5'
